name: Build and Create Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Git safe directory
        run: git config --global --add safe.directory /home/runner/work/postman-codegen/postman-codegen

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.8.1'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Run build step
        run: npm run build

      - name: Create release branch
        run: |
          # Create a new release branch from main
          RELEASE_TAG="${GITHUB_REF_NAME:-${GITHUB_REF##*/}}"  # fallback for old runtime
          RELEASE_BRANCH="release/${RELEASE_TAG}"
          git checkout -b "$RELEASE_BRANCH"
          git push origin "$RELEASE_BRANCH"

      - name: Create Pull Request to merge release into main
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
          echo "${{ secrets.GH_PAT }}" | gh auth login --with-token

          RELEASE_BRANCH="release/${GITHUB_REF##*/}"
          VERSION_LABEL="${GITHUB_REF##*/}"
          
          # Create PR
          gh pr create \
            --base dev \
            --head "$RELEASE_BRANCH" \
            --title "Merge release into main" \
            --body "Auto-generated PR to merge release branch into main."

          # Add label (e.g., "v1.2.3")
          PR_NUMBER=$(gh pr list --head "$RELEASE_BRANCH" --json number -q '.[0].number')
          gh pr edit "$PR_NUMBER" --add-label "$VERSION_LABEL"

