name: Build and Create Release

on:
  pull_request:
    types:
      - closed
  
permissions:
  contents: write

jobs:
  create-release:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.base.ref, 'main') && !startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Git safe directory
        run: git config --global --add safe.directory /home/runner/work/postman-codegen/postman-codegen
      
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create release branch
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            # Check if PR has tag-like label
            LABEL=$(gh pr view ${{ github.event.pull_request.number }} --json labels -q '.labels[].name' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$')
            if [ -n "$LABEL" ]; then
              git checkout -b "release/$LABEL"
              git config user.name "github-actions[bot]"
              git config user.email "github-actions[bot]@users.noreply.github.com"
              echo "Trigger release for $LABEL" >> .github/RELEASE_LOG.md
              git add .github/RELEASE_LOG.md
              git commit -m "chore(release): prepare release $LABEL"
              git push origin "release/$LABEL"
            fi
          fi

      - name: Create Pull Request to merge release into main
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

          LABEL=$(gh pr view ${{ github.event.pull_request.number }} --json labels -q '.labels[].name' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$')
          RELEASE_BRANCH="release/${LABEL}"
          
          # Create PR
          gh pr create \
            --base main
            --head "$RELEASE_BRANCH" \
            --title "Release $LABEL" \
            --body "Auto-generated PR to merge release \`$RELEASE_BRANCH\` into main."

          # Add label (e.g., "v1.2.3")
          PR_NUMBER=$(gh pr list --head "$RELEASE_BRANCH" --json number -q '.[0].number')
          gh pr edit "$PR_NUMBER" --add-label "$LABEL"

