name: Trigger release

# on:
#   push:
#     branches:
#       - main // On process if you want use semantic release
  
permissions:
  contents: write
  pull-requests: write

jobs:
  tigger-release:
     if: contains(github.event.head_commit.message, '/release/')
     runs-on: ubuntu-latest
     steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Git safe directory
        run: git config --global --add safe.directory /home/runner/work/postman-codegen/postman-codegen

      - name: Trigger release publish npm
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_CLASSIC }}
        run: |
          echo "✅ Commit merged from release/* — triggering publish"
          curl -X POST https://api.github.com/repos/${{ github.repository }}/actions/workflows/publish-npm.yaml/dispatches \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${GH_TOKEN}" \
            -d '{"ref":"main"}'
          
    

