name: Trigger release

on:
  push:
    branches:
      - main
  
permissions:
  contents: write
  pull-requests: write

jobs:
  tigger-release:
     if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.base.ref, 'main') && startsWith(github.event.pull_request.head.ref, 'release/')
     runs-on: ubuntu-latest
     steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Git safe directory
        run: git config --global --add safe.directory /home/runner/work/postman-codegen/postman-codegen

      - name: Check if last commit is merge from release/*
        id: check_merge
        run: |
          LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Last commit message: $LAST_COMMIT_MSG"
          if echo "$LAST_COMMIT_MSG" | grep -qE "Merge pull request #[0-9]+ from release/"; then
            echo "is_release_merge=true" >> $GITHUB_OUTPUT
          else
            echo "is_release_merge=false" >> $GITHUB_OUTPUT
          fi

      - name: Trigger release publish npm
        if: steps.check_merge.outputs.is_release_merge == 'true'
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_CLASSIC }}
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
              curl -X POST https://api.github.com/repos/${{ github.repository }}/actions/workflows/publish-npm.yaml/dispatches \
                -H "Accept: application/vnd.github.v3+json" \
                -H "Authorization: token ${GH_TOKEN}" \
                -d '{"ref":"main"}'
          fi
    

